---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}:{{ .Values.wordpress.imageTag }}
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: {{ .Values.db.user.username }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.db.user.password }}
        ports:
        - containerPort: 80
          name: http
